### PR TITLE
OMDB API added

### PR DESCRIPTION
**Pull request by viralvaghela**
- Added OMDB API
- Changed path of github API from viralvaghela/github_api.dart to /viralvaghela/github api/github_api.dart

### CODE REVIEW

**Comment by suffisme** [comment]
@shivanshuman021 Look this PR

**Comment by shivanshuman021** [comment]
@ashiqa

**Comment by shivanshuman021** [comment]
> @shivanshuman021 Look into this PR

Looks good to me

**Comment by ashiqa** [comment]
vokay vro

**Pull request merged**
