### PR TITLE
Intractive Video - Youtube IFrame Player API

### PR DESCRIPTION
**Pull request by ask2rg**
Use YouTube IFrame Player API to make youtube video Interactive or we can say video quiz, i just make a prototype. we can add polls, mcq, feedback or more,  this is also work on live video.
image

### CODE REVIEW

**Comment by shivanshuman021** [comment]
@ask2rg Please add a small demo of the project if possible.

**Comment by ask2rg** [comment]
@suffisme  i put both project in Technocrats-HacktoberFest/JavaScript/, if there are any conflict please can you help me to fix it

**Comment by ask2rg** [comment]
@shivanshuman021 i add two project both are completely different 
first is for Interactive YouTube Video - where some html button show on video (on specific time) when question ask on video. you need to choose correct  option.

second is bookmarklet for calculate total duration of YouTube playlist, this is very helpful for me  to identify easily how much time playlist will be taken when i select a course playlist

**Comment by ask2rg** [comment]
> @ask2rg Please add a small demo of the project if possible.

For whom ? Do I have to create separate pull requests for both the projects

**Comment by shivanshuman021** [comment]
@ask2rg for the first one ,add the demo.

Edit in this pull request only

**Comment by suffisme** [comment]
Heyy, @ask2rg 
we already changed some folder names.
What I would suggest it
You can close this PR, and add properly in the folders.

Actually if you would go to the JavaScript folder, you will find one file present in directory not in your folder (that u created)

 For ur ease, simply save those codes somewhere and pull and fetch upstream and then make a proper folder and add those codes.

And if possible a demo, as @shivanshuman021  suggested.

Thanks,
Team Technocrats.

You can contact me for any confusions.
no worries

**Comment by shivanshuman021** [comment]
@ask2rg  Actually I liked u PR so much that I want to see it working
so Asked for demo.

if u are free then only make a demo.
else chill man, u r doing grt. 

Wishes,
Anshuman
Team Technocrats

**Comment by ask2rg** [comment]
@suffisme @shivanshuman021 yes actually we need to close this pull request, and i will create two new pull request for each project, and for Intractive youtube video project i will work more and also add demo also

even i get some more ideas for interactive YouTube video project we can also connect Firebase so can change in real time but i need to test it first

**Pull request closed without merging**
