### PR TITLE
a python file to check flight prices using selenium

### PR DESCRIPTION
**Pull request by VishnuChebolu**
Using selenium

### CODE REVIEW

**Comment by VishnuChebolu** [comment]
sure! will do that

**Comment by VishnuChebolu** [comment]
updates are done, can u pls look into it

**Comment by suffisme** [comment]
Thanks for contributing @VishnuChebolu 

Wishes & Regards,
Team Technocrats

**Comment by VishnuChebolu** [comment]
Thank you for your support!

**Pull request merged**
