### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by ankur12-1610**
Added README.md to the uploaded code.

### CODE REVIEW

**Comment by ankur12-1610** [comment]
@shivanshuman021 now is it okay?

**Comment by suffisme** [comment]
Not that @ankur12-1610 
I meant 
the readme regarding your code only.

That README.md you added is already there I guess!

**Comment by ankur12-1610** [comment]
> Not that @ankur12-1610 I meant the readme regarding your code only.
> 
> That README.md you added is already there I guess!

Okay so like if I give a description of it will that be okay?

**Comment by suffisme** [comment]
Yeah seems fine
putting in README.md would beautify it.
I hope you get it

**Comment by suffisme** [comment]
Do comment / mention me here after you are done and i will remove the pending label and merge it to code.

**Comment by ankur12-1610** [comment]
@suffisme can you check it now!

**Comment by suffisme** [comment]
Yeah Seems fine

**Comment by ankur12-1610** [comment]
> Yeah Seems fine

Thank you!

**Pull request merged**
